name: JSON Check

on:
  push:
    paths:
      - '**.json'

jobs:
  validate-json:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install python3
      - name: Validate JSON
        run: |
          for file in $(find . -type f -name "*.json"); do
            python3 -m json.tool "$file" > /dev/null
          done