name: JSON Check

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - '**.json'

jobs:
  validate-json:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install python3
      - name: Validate JSON
        run: |
          find . -type f -name "*.json" -print0 | xargs -0 -n1 sh -c '
            file="$0"
            if ! python3 -m json.tool "$file" > tmpfile 2>&1; then
              echo "Error in JSON file $file: $(cat tmpfile)"
              rm tmpfile
              exit 1
            fi'