name: JSON syntax check

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - '**.json'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Find JSON files
        run: |
          find . -name '*.json' -print0 | xargs -0 -r -L 1 sh -c '
            for file do
              if ! python3 -m json.tool "$file" >/dev/null 2>&1; then
                echo "$file"
              fi
            done' sh
        id: failed-files
      - name: Comment failed files
        if: always()
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const failedFiles = `${{ steps.failed-files.outputs.stdout }}`;
            if (failedFiles) {
              const message = `The following JSON files have syntax errors:\n\`\`\`${failedFiles}\`\`\``;
              github.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: message
              });
            }